// Timestamp formatting for generated PDFs.
//
// Every PDF in this app is rendered server-side — most of them from a cron
// route, which runs in UTC on Vercel. A bare `toLocaleString()` therefore
// stamps UTC onto a document that a rink reads as its own local record, which
// misstates the time and can name the wrong day entirely. That is the rule in
// CLAUDE.md ("never format a time without an explicit timeZone") applied to
// the one layer that had never honored it.
//
// The facility's zone reaches every template through `PdfMetaHeaderData.timeZone`
// (resolved once in resolveMetaHeader, which already queries `facilities`), so
// these helpers just need the string handed to them.
//
// Deliberately pure and free of `server-only` imports so it is unit-testable
// under vitest's plain-Node environment — see format.test.ts.

import { formatInTz } from "@/lib/timezone"

/** Placeholder used wherever a record has no timestamp to show. */
const EMPTY = "—"

/**
 * A record timestamp (submitted at, occurred at, resolved at …) rendered in the
 * facility's wall clock. A null/blank value renders as an em dash; an
 * unparseable one is returned unchanged by formatInTz rather than becoming
 * "Invalid Date".
 */
export function formatPdfTimestamp(
  iso: string | null | undefined,
  timeZone: string | null,
): string {
  if (!iso) return EMPTY
  return formatInTz(iso, timeZone)
}

/**
 * The "Generated by Rink Reports · … · <when>" stamp in every PDF footer.
 * Same zone as the record timestamps above, so a reader isn't comparing two
 * different clocks on one page.
 */
export function formatPdfGeneratedAt(now: Date, timeZone: string | null): string {
  return formatInTz(now, timeZone)
}
