import "server-only"

import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer"
import React from "react"

import type { SubmissionSnapshot } from "./snapshot"

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    color: "#0f172a",
    fontFamily: "Helvetica",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#94a3b8",
    paddingBottom: 12,
    marginBottom: 16,
  },
  title: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#475569" },
  meta: { fontSize: 9, color: "#64748b", marginTop: 6 },
  section: { marginBottom: 14 },
  sectionLabel: {
    fontSize: 10,
    color: "#64748b",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  row: { flexDirection: "row", marginBottom: 4 },
  rowLabel: { width: 130, color: "#475569" },
  rowValue: { flex: 1, color: "#0f172a" },
  body: {
    fontSize: 11,
    lineHeight: 1.45,
    color: "#0f172a",
  },
  footer: {
    position: "absolute",
    left: 40,
    right: 40,
    bottom: 24,
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 6,
  },
})

function SubmissionPdf({ snapshot }: { snapshot: SubmissionSnapshot }) {
  const submittedAt = snapshot.submitted_at
    ? new Date(snapshot.submitted_at).toLocaleString()
    : "—"
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{snapshot.title}</Text>
          {snapshot.subtitle ? (
            <Text style={styles.subtitle}>{snapshot.subtitle}</Text>
          ) : null}
          <Text style={styles.meta}>
            Submitted {submittedAt} · Record {snapshot.source_record_id}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Details</Text>
          {snapshot.fields.map((f, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.rowLabel}>{f.label}</Text>
              <Text style={styles.rowValue}>{f.value ?? "—"}</Text>
            </View>
          ))}
        </View>

        {snapshot.long_form ? (
          <View style={styles.section}>
            <Text style={styles.sectionLabel}>{snapshot.long_form.label}</Text>
            <Text style={styles.body}>{snapshot.long_form.body}</Text>
          </View>
        ) : null}

        <Text style={styles.footer} fixed>
          Generated by Rink Reports · {snapshot.source_module} ·{" "}
          {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  )
}

/**
 * Render a SubmissionSnapshot to a PDF buffer. Throws on render failure;
 * callers must catch and degrade gracefully (the cron route logs and
 * leaves pdf_url null so the message still sends without an attachment).
 */
export async function renderSubmissionPdf(
  snapshot: SubmissionSnapshot,
): Promise<Buffer> {
  return await renderToBuffer(<SubmissionPdf snapshot={snapshot} />)
}
