// Pure occurrence generation for recurring booking series.
//
// Dependency-free apart from src/lib/timezone.ts (Intl only), so vitest runs it
// in plain Node.
//
// THE DST RULE, which is the whole reason this file is careful. A weekly
// contract is written in WALL CLOCK: "Tuesdays, 6pm to 8pm, all season". When
// the clocks change, the customer still turns up at 6pm. So each occurrence is
// generated by taking its own local date and resolving THAT date's 18:00 to a
// UTC instant — never by adding 7×24h to the previous instant, which would
// silently shift the slot by an hour for half the season.
//
// The same reasoning applies to pricing: each occurrence resolves its own rate
// card by its own date, so a series spanning a rate change is billed correctly
// on both sides without anyone re-entering it.

import { addDaysToKey, wallTimeToUtc, weekdayOfKey } from "@/lib/timezone"

export type RecurrenceSpec = {
  /** 0 = Sunday .. 6 = Saturday, matching facility_operating_hours. */
  daysOfWeek: number[]
  /** Facility-local wall clock, "HH:MM". */
  startTime: string
  endTime: string
  /** Inclusive, YYYY-MM-DD in facility-local terms. */
  seriesStartDate: string
  seriesEndDate: string
  /** 1 = every week, 2 = fortnightly, ... */
  intervalWeeks: number
}

export type Occurrence = {
  dayKey: string
  startsAt: string
  endsAt: string
  /** True when the slot runs past local midnight into the next day. */
  crossesMidnight: boolean
}

/** Hard ceiling on how many occurrences one series may generate. A weekly
 *  contract on 7 days for 2 years is ~730; anything beyond this is a typo in
 *  the date range, and generating it would lock the table for a long time. */
export const MAX_OCCURRENCES = 400

export type GenerateResult =
  | { ok: true; occurrences: Occurrence[] }
  | { ok: false; error: string }

function parseHm(value: string): number | null {
  const m = /^(\d{1,2}):(\d{2})(?::(\d{2}))?$/.exec(value.trim())
  if (!m) return null
  const h = Number(m[1])
  const min = Number(m[2])
  if (h > 23 || min > 59) return null
  return h * 60 + min
}

function isDateKey(v: string): boolean {
  return /^\d{4}-\d{2}-\d{2}$/.test(v)
}

/**
 * Expand a weekly recurrence into concrete UTC instants.
 *
 * Every occurrence is resolved independently against its own local date, which
 * is what keeps a 6pm slot at 6pm across a DST boundary.
 */
export function generateOccurrences(
  spec: RecurrenceSpec,
  timeZone: string | null,
): GenerateResult {
  if (!isDateKey(spec.seriesStartDate) || !isDateKey(spec.seriesEndDate)) {
    return { ok: false, error: "Enter a valid start and end date for the series." }
  }
  if (spec.seriesEndDate < spec.seriesStartDate) {
    return { ok: false, error: "The series end date cannot fall before its start date." }
  }
  if (spec.daysOfWeek.length === 0) {
    return { ok: false, error: "Pick at least one day of the week." }
  }
  if (spec.daysOfWeek.some((d) => d < 0 || d > 6)) {
    return { ok: false, error: "Day of week must be between 0 (Sunday) and 6 (Saturday)." }
  }
  if (!Number.isInteger(spec.intervalWeeks) || spec.intervalWeeks < 1 || spec.intervalWeeks > 12) {
    return { ok: false, error: "Repeat every 1 to 12 weeks." }
  }

  const startMin = parseHm(spec.startTime)
  const endMin = parseHm(spec.endTime)
  if (startMin === null) return { ok: false, error: "Start time must look like 18:00." }
  if (endMin === null) return { ok: false, error: "End time must look like 20:00." }
  if (endMin === startMin) {
    return { ok: false, error: "The start and end time are the same." }
  }

  // An end time before the start time means the slot runs past midnight — a
  // late-night rental is legitimate, so it lands on the following local day.
  const crossesMidnight = endMin < startMin
  const wanted = new Set(spec.daysOfWeek)

  // "Every N weeks" is measured from the week containing the series start, so
  // fortnightly means the same weeks the customer expects rather than drifting
  // with whichever day happens to come first.
  const anchorWeekStart = addDaysToKey(
    spec.seriesStartDate,
    -weekdayOfKey(spec.seriesStartDate),
  )

  const occurrences: Occurrence[] = []
  let dayKey = spec.seriesStartDate
  let guard = 0

  while (dayKey <= spec.seriesEndDate) {
    // Cheap infinity guard: the loop advances one day at a time, so this can
    // only trip on a pathological range.
    if (++guard > 4000) break

    if (wanted.has(weekdayOfKey(dayKey))) {
      const weekStart = addDaysToKey(dayKey, -weekdayOfKey(dayKey))
      const weeksSinceAnchor = Math.round(
        (Date.parse(`${weekStart}T00:00:00Z`) -
          Date.parse(`${anchorWeekStart}T00:00:00Z`)) /
          (7 * 86_400_000),
      )

      if (weeksSinceAnchor >= 0 && weeksSinceAnchor % spec.intervalWeeks === 0) {
        const startDate = wallTimeToUtc(`${dayKey}T${spec.startTime}`, timeZone)
        const endDayKey = crossesMidnight ? addDaysToKey(dayKey, 1) : dayKey
        const endDate = wallTimeToUtc(`${endDayKey}T${spec.endTime}`, timeZone)

        if (startDate && endDate && endDate.getTime() > startDate.getTime()) {
          occurrences.push({
            dayKey,
            startsAt: startDate.toISOString(),
            endsAt: endDate.toISOString(),
            crossesMidnight,
          })
          if (occurrences.length > MAX_OCCURRENCES) {
            return {
              ok: false,
              error: `That range would create more than ${MAX_OCCURRENCES} bookings. Shorten the date range or reduce the days selected.`,
            }
          }
        }
      }
    }

    dayKey = addDaysToKey(dayKey, 1)
  }

  if (occurrences.length === 0) {
    return {
      ok: false,
      error: "That pattern produces no dates. Check the days of the week against the date range.",
    }
  }

  return { ok: true, occurrences }
}

/** How a user chose to deal with an occurrence the database would refuse. */
export type OccurrenceResolution =
  | { kind: "book" }
  | { kind: "skip" }
  /** Shift this one occurrence by N minutes, both ends. */
  | { kind: "shift"; minutes: number }

export type PlannedOccurrence = Occurrence & {
  resolution: OccurrenceResolution
  conflict: boolean
}

/** Apply a per-occurrence shift, preserving duration. Returns null for a
 *  skipped occurrence so callers can filter in one pass. */
export function applyResolution(
  occurrence: PlannedOccurrence,
): { startsAt: string; endsAt: string } | null {
  if (occurrence.resolution.kind === "skip") return null
  if (occurrence.resolution.kind === "book") {
    return { startsAt: occurrence.startsAt, endsAt: occurrence.endsAt }
  }
  const delta = occurrence.resolution.minutes * 60_000
  return {
    startsAt: new Date(new Date(occurrence.startsAt).getTime() + delta).toISOString(),
    endsAt: new Date(new Date(occurrence.endsAt).getTime() + delta).toISOString(),
  }
}

/** A short human summary of the pattern, for the confirmation step. */
export function describeRecurrence(spec: RecurrenceSpec): string {
  const names = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
  const days = [...spec.daysOfWeek].sort((a, b) => a - b).map((d) => names[d]).join(", ")
  const every =
    spec.intervalWeeks === 1
      ? "Every week"
      : spec.intervalWeeks === 2
        ? "Every other week"
        : `Every ${spec.intervalWeeks} weeks`
  return `${every} on ${days}, ${spec.startTime}–${spec.endTime}, ${spec.seriesStartDate} to ${spec.seriesEndDate}`
}
