import "server-only"

import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer"
import React from "react"

import type { ExportSettingsRow } from "@/app/admin/exports/types"

import type { ExportTable } from "./types"

const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 48,
    paddingHorizontal: 28,
    fontSize: 8,
    color: "#0f172a",
    fontFamily: "Helvetica",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#94a3b8",
    paddingBottom: 8,
    marginBottom: 12,
  },
  brand: { fontSize: 9, color: "#475569", marginBottom: 2 },
  title: { fontSize: 16, fontWeight: 700 },
  meta: { fontSize: 8, color: "#64748b", marginTop: 4 },
  table: { width: "100%" },
  headRow: {
    flexDirection: "row",
    backgroundColor: "#e2e8f0",
    borderBottomWidth: 1,
    borderBottomColor: "#94a3b8",
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  rowAlt: { backgroundColor: "#f8fafc" },
  headCell: {
    paddingVertical: 4,
    paddingHorizontal: 4,
    fontWeight: 700,
    fontSize: 8,
    color: "#0f172a",
  },
  cell: {
    paddingVertical: 3,
    paddingHorizontal: 4,
    fontSize: 8,
    color: "#0f172a",
  },
  empty: { fontSize: 10, color: "#64748b", marginTop: 24, textAlign: "center" },
  footer: {
    position: "absolute",
    left: 28,
    right: 28,
    bottom: 20,
    fontSize: 7,
    color: "#94a3b8",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 5,
  },
})

function pageSize(paper: ExportSettingsRow["paper_size"]): "LETTER" | "A4" {
  return paper === "a4" ? "A4" : "LETTER"
}

/** Even column widths as flex weights so wide tables stay within the page. */
function colFlex(count: number): number {
  return count > 0 ? 1 / count : 1
}

function GenericTablePdf({
  table,
  settings,
  rangeLabel,
}: {
  table: ExportTable
  settings: ExportSettingsRow
  rangeLabel: string
}) {
  const cols = table.headers.length
  const flex = colFlex(cols)
  const footer =
    settings.footer_text?.trim() ||
    `Generated by Rink Reports · ${table.module}`

  return (
    <Document>
      <Page size={pageSize(settings.paper_size)} style={styles.page} wrap orientation="landscape">
        <View style={styles.header}>
          {settings.header_text?.trim() ? (
            <Text style={styles.brand}>{settings.header_text.trim()}</Text>
          ) : null}
          <Text style={styles.title}>{table.title}</Text>
          <Text style={styles.meta}>
            {rangeLabel} · {table.rows.length} record
            {table.rows.length === 1 ? "" : "s"}
          </Text>
        </View>

        {table.rows.length === 0 ? (
          <Text style={styles.empty}>No records in the selected range.</Text>
        ) : (
          <View style={styles.table}>
            <View style={styles.headRow} fixed>
              {table.headers.map((h, i) => (
                <Text key={i} style={{ ...styles.headCell, flexBasis: 0, flexGrow: flex }}>
                  {h}
                </Text>
              ))}
            </View>
            {table.rows.map((row, ri) => (
              <View
                key={ri}
                style={ri % 2 === 1 ? { ...styles.row, ...styles.rowAlt } : styles.row}
                wrap={false}
              >
                {row.map((cell, ci) => (
                  <Text key={ci} style={{ ...styles.cell, flexBasis: 0, flexGrow: flex }}>
                    {cell}
                  </Text>
                ))}
              </View>
            ))}
          </View>
        )}

        <Text
          style={styles.footer}
          fixed
          render={({ pageNumber, totalPages }) =>
            `${footer} · ${new Date().toLocaleString()} · Page ${pageNumber} of ${totalPages}`
          }
        />
      </Page>
    </Document>
  )
}

/**
 * Render a date-range ExportTable to a tabular PDF buffer, honoring branding
 * (header/footer text) and paper size from export settings. Generic across
 * modules; @react-pdf is imported here only, in a "server-only" module, so it
 * never reaches the client bundle.
 */
export async function renderTablePdf(
  table: ExportTable,
  settings: ExportSettingsRow,
  rangeLabel: string,
): Promise<Buffer> {
  return await renderToBuffer(
    <GenericTablePdf table={table} settings={settings} rangeLabel={rangeLabel} />,
  )
}
