"use client"

import { useActionState, useState } from "react"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"

import { saveExportSettings } from "../actions"
import type { ActionState, ExportSettingsRow } from "../types"
import { PAPER_SIZES } from "../types"

const INITIAL: ActionState = { ok: null }

interface Props {
  settings: ExportSettingsRow | null
}

export function ExportSettingsForm({ settings }: Props) {
  const [state, formAction, pending] = useActionState(saveExportSettings, INITIAL)
  const [paperSize, setPaperSize] = useState<string>(settings?.paper_size ?? "letter")

  return (
    <form action={formAction} className="flex flex-col gap-6">
      <Card>
        <CardHeader>
          <CardTitle>Branding</CardTitle>
          <CardDescription>
            Logo and text that appear on exported PDFs.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="logo_url">Logo URL</Label>
            <Input
              id="logo_url"
              name="logo_url"
              type="url"
              placeholder="https://example.com/logo.png"
              defaultValue={settings?.logo_url ?? ""}
            />
            <p className="text-xs text-muted-foreground">
              Publicly accessible image URL. Recommended size: 300 × 80 px.
            </p>
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="header_text">Header text</Label>
            <Textarea
              id="header_text"
              name="header_text"
              rows={2}
              placeholder="e.g. Max Ice Center — Confidential"
              defaultValue={settings?.header_text ?? ""}
            />
          </div>

          <div className="flex flex-col gap-1.5">
            <Label htmlFor="footer_text">Footer text</Label>
            <Textarea
              id="footer_text"
              name="footer_text"
              rows={2}
              placeholder="e.g. Generated by Rink Reports · Not for public distribution"
              defaultValue={settings?.footer_text ?? ""}
            />
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Layout</CardTitle>
          <CardDescription>
            Paper size and default field visibility.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-4">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="paper_size">Paper size</Label>
            <input type="hidden" name="paper_size" value={paperSize} />
            <Select value={paperSize} onValueChange={(v) => setPaperSize(v)}>
              <SelectTrigger id="paper_size" className="w-fit min-w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {PAPER_SIZES.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-col gap-2">
            <span className="text-sm font-medium">Include on every export</span>
            <CheckboxField
              name="include_facility_name"
              label="Facility name"
              defaultChecked={settings?.include_facility_name ?? true}
            />
            <CheckboxField
              name="include_date"
              label="Export date"
              defaultChecked={settings?.include_date ?? true}
            />
            <CheckboxField
              name="include_submitted_by"
              label="Submitted-by name"
              defaultChecked={settings?.include_submitted_by ?? true}
            />
          </div>
        </CardContent>
      </Card>

      {state.ok === false && (
        <p className="text-sm text-destructive">{state.error}</p>
      )}
      {state.ok === true && (
        <p className="text-sm text-green-600 dark:text-green-400">
          {state.message}
        </p>
      )}

      <div>
        <Button type="submit" disabled={pending}>
          {pending ? "Saving…" : "Save export settings"}
        </Button>
      </div>
    </form>
  )
}

function CheckboxField({
  name,
  label,
  defaultChecked,
}: {
  name: string
  label: string
  defaultChecked: boolean
}) {
  return (
    <div className="flex items-center gap-2">
      <input
        type="checkbox"
        id={name}
        name={name}
        defaultChecked={defaultChecked}
        className="h-4 w-4 rounded border"
      />
      <Label htmlFor={name} className="cursor-pointer font-normal">
        {label}
      </Label>
    </div>
  )
}
