-- =============================================================================
-- Automatic locker-room cleaning work generated by Rink Scheduling.
--
-- One task belongs to one booking (not one room): all rooms assigned to the
-- rental are presented together to the employee.  Reconciliation is database
-- driven so every booking write path (UI, series expansion, API and imports)
-- gets identical, transactionally consistent behaviour.
-- =============================================================================

begin;

-- Migration 00280 already introduced a per-locker-room version of this table.
-- Preserve its history, remove its reconciliation hooks, and replace it with
-- the booking-scoped model.  Editing 00280 would break clean replay and would
-- not upgrade databases where that migration has already run.
create temporary table locker_room_cleaning_tasks_upgrade_data
on commit drop
as
select
  (array_agg(t.id order by t.created_at, t.id))[1] as id,
  t.facility_id,
  t.booking_id,
  (array_agg(t.assigned_employee_id order by t.created_at, t.id)
    filter (where t.assigned_employee_id is not null))[1] as assigned_employee_id,
  max(t.scheduled_for) as scheduled_for,
  array_agg(t.locker_room_id order by lr.sort_order, lr.name, t.locker_room_id) as locker_room_ids,
  array_agg(lr.name order by lr.sort_order, lr.name, t.locker_room_id) as locker_room_names,
  coalesce(
    (array_agg(t.assignment_route order by t.created_at, t.id)
      filter (where t.assignment_route in ('custodial', 'manager')))[1],
    'unassigned'
  ) as assignment_route,
  case
    when bool_or(t.status = 'completed') then 'completed'
    when bool_and(t.status = 'cancelled') then 'cancelled'
    else 'pending'
  end as status,
  case when bool_or(t.status = 'completed') then max(t.completed_at) end as completed_at,
  case when bool_and(t.status = 'cancelled')
       then coalesce(max(t.cancelled_at), now()) end as cancelled_at,
  min(t.created_at) as created_at,
  max(t.updated_at) as updated_at
from public.locker_room_cleaning_tasks t
join public.rink_bookings b
  on b.id = t.booking_id and b.facility_id = t.facility_id
join public.facility_locker_rooms lr
  on lr.id = t.locker_room_id and lr.facility_id = t.facility_id
where t.booking_id is not null
group by t.facility_id, t.booking_id;

drop trigger if exists trg_reconcile_locker_room_cleaning_assignment
  on public.rink_locker_room_assignments;
drop trigger if exists trg_reconcile_locker_room_cleaning_booking
  on public.rink_bookings;
drop function if exists public.reconcile_locker_room_cleaning_task_trigger();
drop function if exists public.reconcile_locker_room_cleaning_task(uuid);
drop policy if exists facility_locker_rooms_select
  on public.facility_locker_rooms;
drop table public.locker_room_cleaning_tasks;

create table public.locker_room_cleaning_tasks (
  id                    uuid primary key default gen_random_uuid(),
  facility_id           uuid not null references public.facilities(id) on delete restrict,
  booking_id            uuid not null,
  assigned_employee_id  uuid references public.employees(id) on delete set null,
  assigned_shift_id     uuid references public.schedule_shifts(id) on delete set null,
  scheduled_for         timestamptz not null,
  locker_room_ids       uuid[] not null,
  locker_room_names     text[] not null,
  assignment_route      text not null,
  status                text not null default 'pending',
  completed_at          timestamptz,
  cancelled_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz,
  constraint locker_room_cleaning_tasks_booking_uniq unique (booking_id),
  constraint locker_room_cleaning_tasks_booking_fk
    foreign key (booking_id, facility_id)
    references public.rink_bookings(id, facility_id) on delete cascade,
  constraint locker_room_cleaning_tasks_rooms_present
    check (cardinality(locker_room_ids) > 0 and cardinality(locker_room_ids) = cardinality(locker_room_names)),
  constraint locker_room_cleaning_tasks_route_check
    check (assignment_route in ('custodial', 'manager', 'unassigned')),
  constraint locker_room_cleaning_tasks_status_check
    check (status in ('pending', 'completed', 'cancelled')),
  constraint locker_room_cleaning_tasks_cancel_coherent
    check ((status = 'cancelled') = (cancelled_at is not null)),
  constraint locker_room_cleaning_tasks_complete_coherent
    check ((status = 'completed') = (completed_at is not null))
);

insert into public.locker_room_cleaning_tasks (
  id, facility_id, booking_id, assigned_employee_id, assigned_shift_id,
  scheduled_for, locker_room_ids, locker_room_names, assignment_route, status,
  completed_at, cancelled_at, created_at, updated_at
)
select
  id, facility_id, booking_id, assigned_employee_id, null,
  scheduled_for, locker_room_ids, locker_room_names, assignment_route, status,
  completed_at, cancelled_at, created_at, updated_at
from locker_room_cleaning_tasks_upgrade_data;

comment on table public.locker_room_cleaning_tasks is
  'Task-system work generated from a rink rental with locker rooms. Exactly one task per booking; scheduled 30 minutes after ice ends and kept in sync by triggers.';
comment on column public.locker_room_cleaning_tasks.scheduled_for is
  'Absolute instant 30 minutes after rink_bookings.ends_at. Render in facilities.timezone; timestamptz keeps DST transitions unambiguous.';
comment on column public.locker_room_cleaning_tasks.assignment_route is
  'custodial when assigned to an on-duty employee in the Custodial job area, manager for the on-duty fallback, or unassigned when neither is rostered.';

create index locker_room_cleaning_tasks_facility_due
  on public.locker_room_cleaning_tasks (facility_id, scheduled_for)
  where status = 'pending';
create index locker_room_cleaning_tasks_employee_due
  on public.locker_room_cleaning_tasks (assigned_employee_id, scheduled_for)
  where status = 'pending' and assigned_employee_id is not null;

create or replace function public.guard_locker_room_cleaning_task_update()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  -- Reconciliation updates are nested below a source-table trigger. Direct
  -- authenticated updates may only mark a task complete; task identity,
  -- routing, timing and room scope remain server-owned.
  if pg_trigger_depth() = 1
     and not public.is_super_admin()
     and coalesce(auth.role(), '') <> 'service_role' then
    if old.status <> 'pending' or new.status <> 'completed'
       or new.facility_id is distinct from old.facility_id
       or new.booking_id is distinct from old.booking_id
       or new.assigned_employee_id is distinct from old.assigned_employee_id
       or new.assigned_shift_id is distinct from old.assigned_shift_id
       or new.scheduled_for is distinct from old.scheduled_for
       or new.locker_room_ids is distinct from old.locker_room_ids
       or new.locker_room_names is distinct from old.locker_room_names
       or new.assignment_route is distinct from old.assignment_route
       or new.cancelled_at is distinct from old.cancelled_at
       or new.created_at is distinct from old.created_at then
      raise exception 'locker room cleaning tasks may only be marked complete'
        using errcode = '42501';
    end if;
    new.completed_at := now();
  end if;
  return new;
end;
$$;
revoke execute on function public.guard_locker_room_cleaning_task_update()
  from public, anon, authenticated;

create trigger trg_locker_room_cleaning_tasks_guard
  before update on public.locker_room_cleaning_tasks
  for each row execute function public.guard_locker_room_cleaning_task_update();

create trigger trg_locker_room_cleaning_tasks_updated_at
  before update on public.locker_room_cleaning_tasks
  for each row execute function public.set_updated_at();

-- Reuse Scheduling's in-app inbox.  The FK gives reconciliation an exact,
-- indexable identity instead of trying to deduplicate on JSON payload text.
alter table public.schedule_notifications
  add column cleaning_task_id uuid
    references public.locker_room_cleaning_tasks(id) on delete cascade;

create unique index schedule_notifications_cleaning_task_uniq
  on public.schedule_notifications (cleaning_task_id)
  where cleaning_task_id is not null;

alter table public.schedule_notifications
  drop constraint if exists schedule_notifications_notification_type_check;
alter table public.schedule_notifications
  add constraint schedule_notifications_notification_type_check
  check (notification_type in (
    'schedule_published','shift_changed','open_shift_available',
    'swap_request_received','swap_approved','swap_denied',
    'time_off_decided','overtime_warning','shift_reminder',
    'swap_expired','claim_expired','shift_drop_requested','shift_drop_decided',
    'locker_room_cleaning'
  ));

-- Pick a published shift which covers the cleaning task's scheduled instant.
-- Custodial qualification comes from the existing active job-area catalog.
-- A qualifying employee must be rostered on the covering shift; a primary
-- Custodial assignment wins, then the result is stable.
create or replace function public.reconcile_locker_room_cleaning_task(p_booking_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_booking       public.rink_bookings%rowtype;
  v_existing      public.locker_room_cleaning_tasks%rowtype;
  v_has_existing  boolean := false;
  v_task_id       uuid;
  v_employee_id   uuid;
  v_shift_id      uuid;
  v_route         text := 'unassigned';
  v_room_ids      uuid[];
  v_room_names    text[];
  v_due           timestamptz;
  v_timezone      text;
  v_message       text;
begin
  select * into v_booking
  from public.rink_bookings
  where id = p_booking_id
  for update;

  if not found then
    return;
  end if;

  select * into v_existing
  from public.locker_room_cleaning_tasks
  where booking_id = p_booking_id;
  v_has_existing := found;

  select
    array_agg(lr.id order by lr.sort_order, lr.name, lr.id),
    array_agg(lr.name order by lr.sort_order, lr.name, lr.id)
  into v_room_ids, v_room_names
  from public.rink_locker_room_assignments a
  join public.facility_locker_rooms lr
    on lr.id = a.locker_room_id and lr.facility_id = a.facility_id
  where a.booking_id = p_booking_id;

  -- Cancellation is retained as task history. Removing the final room has the
  -- same operational effect; re-adding a room reactivates the unique task.
  if v_booking.status = 'cancelled' or coalesce(cardinality(v_room_ids), 0) = 0 then
    update public.locker_room_cleaning_tasks
    set status = 'cancelled', cancelled_at = coalesce(cancelled_at, now()),
        completed_at = null,
        assigned_employee_id = null, assigned_shift_id = null,
        assignment_route = 'unassigned'
    where booking_id = p_booking_id and status <> 'cancelled'
    returning id into v_task_id;

    if v_task_id is not null then
      delete from public.schedule_notifications where cleaning_task_id = v_task_id;
    end if;
    return;
  end if;

  -- Completed work is immutable history unless its source rental is cancelled
  -- or loses every locker room (handled above).
  if v_has_existing and v_existing.status = 'completed' then
    return;
  end if;

  v_due := v_booking.ends_at + interval '30 minutes';

  select s.employee_id, s.id
  into v_employee_id, v_shift_id
  from public.schedule_shifts s
  join public.employees e
    on e.id = s.employee_id and e.facility_id = s.facility_id and e.is_active
  join public.employee_job_area_assignments ejaa
    on ejaa.employee_id = e.id and ejaa.facility_id = s.facility_id
  join public.employee_job_areas ja
    on ja.id = ejaa.job_area_id and ja.facility_id = s.facility_id
       and ja.is_active and ja.slug = 'custodial'
  where s.facility_id = v_booking.facility_id
    and s.status = 'published'
    and s.starts_at <= v_due and s.ends_at > v_due
  order by ejaa.is_primary desc, s.starts_at desc, s.id
  limit 1;

  if v_employee_id is not null then
    v_route := 'custodial';
  else
    select s.employee_id, s.id
    into v_employee_id, v_shift_id
    from public.schedule_shifts s
    join public.employees e
      on e.id = s.employee_id and e.facility_id = s.facility_id and e.is_active
    join public.roles r
      on r.id = e.role_id and r.facility_id = e.facility_id and r.key = 'manager'
    where s.facility_id = v_booking.facility_id
      and s.status = 'published'
      and s.starts_at <= v_due and s.ends_at > v_due
    order by s.starts_at desc, s.id
    limit 1;
    if v_employee_id is not null then
      v_route := 'manager';
    end if;
  end if;

  -- Shift triggers may revisit many nearby tasks. Do not replace a read inbox
  -- item with an identical unread one when no task-visible value changed.
  if v_has_existing and v_existing.status = 'pending'
     and v_existing.assigned_employee_id is not distinct from v_employee_id
     and v_existing.assigned_shift_id is not distinct from v_shift_id
     and v_existing.scheduled_for = v_due
     and v_existing.locker_room_ids = v_room_ids
     and v_existing.locker_room_names = v_room_names
     and v_existing.assignment_route = v_route then
    return;
  end if;

  insert into public.locker_room_cleaning_tasks (
    facility_id, booking_id, assigned_employee_id, assigned_shift_id,
    scheduled_for, locker_room_ids, locker_room_names,
    assignment_route, status, cancelled_at, completed_at
  ) values (
    v_booking.facility_id, v_booking.id, v_employee_id, v_shift_id,
    v_due, v_room_ids, v_room_names, v_route, 'pending', null, null
  )
  on conflict (booking_id) do update set
    assigned_employee_id = excluded.assigned_employee_id,
    assigned_shift_id = excluded.assigned_shift_id,
    scheduled_for = excluded.scheduled_for,
    locker_room_ids = excluded.locker_room_ids,
    locker_room_names = excluded.locker_room_names,
    assignment_route = excluded.assignment_route,
    status = case when locker_room_cleaning_tasks.status = 'completed'
                  then 'completed' else 'pending' end,
    cancelled_at = case when locker_room_cleaning_tasks.status = 'completed'
                        then locker_room_cleaning_tasks.cancelled_at else null end
  returning id into v_task_id;

  -- Replace rather than append when the booking time, rooms or assignee change.
  delete from public.schedule_notifications where cleaning_task_id = v_task_id;
  if v_employee_id is not null then
    select timezone into v_timezone from public.facilities where id = v_booking.facility_id;
    v_message := format(
      'Clean %s at %s (%s).',
      array_to_string(v_room_names, ', '),
      to_char(v_due at time zone v_timezone, 'FMHH12:MI AM'),
      v_timezone
    );
    insert into public.schedule_notifications (
      facility_id, employee_id, notification_type, shift_id, cleaning_task_id, payload
    ) values (
      v_booking.facility_id, v_employee_id, 'locker_room_cleaning', v_shift_id, v_task_id,
      jsonb_build_object(
        'message', v_message, 'booking_id', v_booking.id,
        'scheduled_for', v_due,
        'timezone', v_timezone, 'locker_rooms', to_jsonb(v_room_names),
        'assignment_route', v_route
      )
    );
  end if;
end;
$$;

comment on function public.reconcile_locker_room_cleaning_task(uuid) is
  'Idempotently creates, reschedules, reroutes or cancels the single cleaning task for a booking. Uses published shifts, active Custodial job-area assignments, and the manager role fallback.';
revoke execute on function public.reconcile_locker_room_cleaning_task(uuid)
  from public, anon, authenticated;

create or replace function public.sync_locker_room_cleaning_from_booking()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  perform public.reconcile_locker_room_cleaning_task(coalesce(new.id, old.id));
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_booking()
  from public, anon, authenticated;

create or replace function public.sync_locker_room_cleaning_from_assignment()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if tg_op = 'UPDATE' and old.booking_id is distinct from new.booking_id then
    perform public.reconcile_locker_room_cleaning_task(old.booking_id);
  end if;
  perform public.reconcile_locker_room_cleaning_task(
    case when tg_op = 'DELETE' then old.booking_id else new.booking_id end
  );
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_assignment()
  from public, anon, authenticated;

create trigger trg_rink_booking_cleaning_sync
  after insert or update of ends_at, status on public.rink_bookings
  for each row execute function public.sync_locker_room_cleaning_from_booking();
create trigger trg_rink_locker_assignment_cleaning_sync
  after insert or update or delete on public.rink_locker_room_assignments
  for each row execute function public.sync_locker_room_cleaning_from_assignment();

-- A roster edit can change the best assignee after the rental was entered.
-- Re-run only pending work whose due instant falls within the changed shift;
-- this also lets a newly published shift claim a previously unassigned task.
create or replace function public.sync_locker_room_cleaning_from_shift()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_task record;
  v_facility_id uuid := coalesce(new.facility_id, old.facility_id);
  v_from timestamptz := least(
    coalesce(new.starts_at, old.starts_at), coalesce(old.starts_at, new.starts_at)
  );
  v_until timestamptz := greatest(
    coalesce(new.ends_at, old.ends_at), coalesce(old.ends_at, new.ends_at)
  );
begin
  for v_task in
    select t.booking_id
    from public.locker_room_cleaning_tasks t
    where t.facility_id = v_facility_id and t.status = 'pending'
      and t.scheduled_for >= v_from and t.scheduled_for < v_until
    order by t.booking_id
  loop
    perform public.reconcile_locker_room_cleaning_task(v_task.booking_id);
  end loop;
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_shift()
  from public, anon, authenticated;

create trigger trg_schedule_shift_cleaning_sync
  after insert or update of employee_id, starts_at, ends_at, status, department_id
  or delete on public.schedule_shifts
  for each row execute function public.sync_locker_room_cleaning_from_shift();

-- Qualification changes can make a current assignee ineligible or make a
-- Custodial employee newly preferable to the manager fallback. These tables
-- change much less often than shifts, so a facility-scoped pass is both
-- simpler and safer than attempting to infer every affected shift here.
create or replace function public.sync_locker_room_cleaning_from_workforce()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_task record;
  v_facility_id uuid := case
    when tg_op = 'DELETE' then old.facility_id
    else new.facility_id
  end;
begin
  for v_task in
    select t.booking_id
    from public.locker_room_cleaning_tasks t
    where t.facility_id = v_facility_id and t.status = 'pending'
    order by t.booking_id
  loop
    perform public.reconcile_locker_room_cleaning_task(v_task.booking_id);
  end loop;
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_workforce()
  from public, anon, authenticated;

create trigger trg_employee_cleaning_sync
  after update of is_active, role_id on public.employees
  for each row execute function public.sync_locker_room_cleaning_from_workforce();
create trigger trg_employee_job_area_assignment_cleaning_sync
  after insert or update or delete on public.employee_job_area_assignments
  for each row execute function public.sync_locker_room_cleaning_from_workforce();
create trigger trg_employee_job_area_cleaning_sync
  after update of is_active, slug on public.employee_job_areas
  for each row execute function public.sync_locker_room_cleaning_from_workforce();

-- Existing confirmed rentals receive tasks during rollout.
do $$
declare v_booking_id uuid;
begin
  for v_booking_id in
    select distinct b.id
    from public.rink_bookings b
    join public.rink_locker_room_assignments a on a.booking_id = b.id
    where b.status <> 'cancelled'
  loop
    perform public.reconcile_locker_room_cleaning_task(v_booking_id);
  end loop;
end;
$$;

alter table public.locker_room_cleaning_tasks enable row level security;

create policy locker_room_cleaning_tasks_select on public.locker_room_cleaning_tasks
  for select to authenticated
  using (
    public.is_super_admin()
    or (facility_id = public.current_facility_id() and (
      assigned_employee_id = public.current_employee_id()
      or public.has_module_edit_access('rink_scheduling')
    ))
  );
create policy locker_room_cleaning_tasks_update on public.locker_room_cleaning_tasks
  for update to authenticated
  using (
    public.is_super_admin()
    or (facility_id = public.current_facility_id() and (
      assigned_employee_id = public.current_employee_id()
      or public.has_module_edit_access('rink_scheduling')
    ))
  )
  with check (public.is_super_admin() or facility_id = public.current_facility_id());

-- Triggers own creation/cancellation; clients cannot forge or delete generated work.
revoke insert, delete on public.locker_room_cleaning_tasks from anon, authenticated;

create trigger trg_audit_locker_room_cleaning_tasks
  after insert or update or delete on public.locker_room_cleaning_tasks
  for each row execute function public.audit_row_change();

-- Recreate the dependent room policy against the booking-scoped room array.
create policy facility_locker_rooms_select on public.facility_locker_rooms
  for select to authenticated
  using (
    public.is_super_admin()
    or (facility_id = public.current_facility_id()
        and public.has_module_access('rink_scheduling'))
    or (facility_id = public.current_facility_id()
        and exists (
          select 1
          from public.locker_room_cleaning_tasks task
          where task.facility_id = facility_locker_rooms.facility_id
            and facility_locker_rooms.id = any(task.locker_room_ids)
            and task.assigned_employee_id = public.current_employee_id()
        ))
  );

commit;
