-- =============================================================================
-- Automatic locker-room cleaning work generated by Rink Scheduling.
--
-- One task belongs to one booking (not one room): all rooms assigned to the
-- rental are presented together to the employee.  Reconciliation is database
-- driven so every booking write path (UI, series expansion, API and imports)
-- gets identical, transactionally consistent behaviour.
-- Audit locker-room cleaning task lifecycle changes.
--
-- The generic audit trigger is deliberately used here, as it is for the other
-- operational tables: it takes facility_id from the changed row, records the
-- authenticated user/employee when there is one, and stores the complete
-- before/after images.  Reconciliation jobs run without an auth JWT, so their
-- audit rows intentionally have NULL actor columns; change_origin preserves an
-- explicit, queryable system/trigger attribution in the audited row image.
-- =============================================================================

begin;

create table public.locker_room_cleaning_tasks (
  id                    uuid primary key default gen_random_uuid(),
  facility_id           uuid not null references public.facilities(id) on delete restrict,
  booking_id            uuid not null,
  assigned_employee_id  uuid references public.employees(id) on delete set null,
  assigned_shift_id     uuid references public.schedule_shifts(id) on delete set null,
  scheduled_for         timestamptz not null,
  locker_room_ids       uuid[] not null,
  locker_room_names     text[] not null,
  assignment_route      text not null,
  status                text not null default 'pending',
  completed_at          timestamptz,
  cancelled_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz,
  constraint locker_room_cleaning_tasks_booking_uniq unique (booking_id),
  constraint locker_room_cleaning_tasks_booking_fk
    foreign key (booking_id, facility_id)
    references public.rink_bookings(id, facility_id) on delete cascade,
  constraint locker_room_cleaning_tasks_rooms_present
    check (cardinality(locker_room_ids) > 0 and cardinality(locker_room_ids) = cardinality(locker_room_names)),
  constraint locker_room_cleaning_tasks_route_check
    check (assignment_route in ('custodial', 'manager', 'unassigned')),
  constraint locker_room_cleaning_tasks_status_check
    check (status in ('pending', 'completed', 'cancelled')),
  constraint locker_room_cleaning_tasks_cancel_coherent
    check ((status = 'cancelled') = (cancelled_at is not null)),
  constraint locker_room_cleaning_tasks_complete_coherent
    check ((status = 'completed') = (completed_at is not null))
);

comment on table public.locker_room_cleaning_tasks is
  'Task-system work generated from a rink rental with locker rooms. Exactly one task per booking; scheduled 30 minutes after ice ends and kept in sync by triggers.';
comment on column public.locker_room_cleaning_tasks.scheduled_for is
  'Absolute instant 30 minutes after rink_bookings.ends_at. Render in facilities.timezone; timestamptz keeps DST transitions unambiguous.';
comment on column public.locker_room_cleaning_tasks.assignment_route is
  'custodial when assigned to an on-duty employee in the Custodial job area, manager for the on-duty fallback, or unassigned when neither is rostered.';

create index locker_room_cleaning_tasks_facility_due
  on public.locker_room_cleaning_tasks (facility_id, scheduled_for)
  where status = 'pending';
create index locker_room_cleaning_tasks_employee_due
  on public.locker_room_cleaning_tasks (assigned_employee_id, scheduled_for)
  where status = 'pending' and assigned_employee_id is not null;

create or replace function public.guard_locker_room_cleaning_task_update()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  -- Reconciliation updates are nested below a source-table trigger. Direct
  -- authenticated updates may only mark a task complete; task identity,
  -- routing, timing and room scope remain server-owned.
  if pg_trigger_depth() = 1
     and not public.is_super_admin()
     and coalesce(auth.role(), '') <> 'service_role' then
    if old.status <> 'pending' or new.status <> 'completed'
       or new.facility_id is distinct from old.facility_id
       or new.booking_id is distinct from old.booking_id
       or new.assigned_employee_id is distinct from old.assigned_employee_id
       or new.assigned_shift_id is distinct from old.assigned_shift_id
       or new.scheduled_for is distinct from old.scheduled_for
       or new.locker_room_ids is distinct from old.locker_room_ids
       or new.locker_room_names is distinct from old.locker_room_names
       or new.assignment_route is distinct from old.assignment_route
       or new.cancelled_at is distinct from old.cancelled_at
       or new.created_at is distinct from old.created_at then
      raise exception 'locker room cleaning tasks may only be marked complete'
        using errcode = '42501';
    end if;
    new.completed_at := now();
  end if;
  return new;
end;
$$;
revoke execute on function public.guard_locker_room_cleaning_task_update()
  from public, anon, authenticated;

create trigger trg_locker_room_cleaning_tasks_guard
  before update on public.locker_room_cleaning_tasks
  for each row execute function public.guard_locker_room_cleaning_task_update();

create trigger trg_locker_room_cleaning_tasks_updated_at
  before update on public.locker_room_cleaning_tasks
  for each row execute function public.set_updated_at();

-- Reuse Scheduling's in-app inbox.  The FK gives reconciliation an exact,
-- indexable identity instead of trying to deduplicate on JSON payload text.
alter table public.schedule_notifications
  add column cleaning_task_id uuid
    references public.locker_room_cleaning_tasks(id) on delete cascade;

create unique index schedule_notifications_cleaning_task_uniq
  on public.schedule_notifications (cleaning_task_id)
  where cleaning_task_id is not null;

alter table public.schedule_notifications
  drop constraint if exists schedule_notifications_notification_type_check;
alter table public.schedule_notifications
  add constraint schedule_notifications_notification_type_check
  check (notification_type in (
    'schedule_published','shift_changed','open_shift_available',
    'swap_request_received','swap_approved','swap_denied',
    'time_off_decided','overtime_warning','shift_reminder',
    'swap_expired','claim_expired','shift_drop_requested','shift_drop_decided',
    'locker_room_cleaning'
  ));

-- Pick a published shift which covers the cleaning task's scheduled instant.
-- Custodial qualification comes from the existing active job-area catalog,
-- and the employee must also belong to the shift's department (not merely
-- share a facility). A primary Custodial assignment wins, then the result is
-- stable.
create or replace function public.reconcile_locker_room_cleaning_task(p_booking_id uuid)
create table if not exists public.locker_room_cleaning_tasks (
  id                    uuid primary key default gen_random_uuid(),
  facility_id           uuid not null references public.facilities(id) on delete restrict,
  locker_room_id        uuid not null,
  booking_id            uuid,
  locker_room_assignment_id uuid,
  scheduled_for         timestamptz not null,
  assigned_employee_id  uuid,
  assignment_route      text,
  status                text not null default 'scheduled'
    check (status in ('scheduled', 'completed', 'cancelled')),
  completed_at          timestamptz,
  completed_by          uuid,
  cancelled_at          timestamptz,
  cancellation_reason   text,
  change_origin         text not null default 'trigger'
    check (change_origin in ('employee', 'manager', 'system', 'trigger')),
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),

  constraint locker_room_cleaning_tasks_id_facility_uniq unique (id, facility_id),
  constraint locker_room_cleaning_tasks_room_fk
    foreign key (locker_room_id, facility_id)
    references public.facility_locker_rooms (id, facility_id) on delete restrict,
  constraint locker_room_cleaning_tasks_booking_fk
    foreign key (booking_id, facility_id)
    references public.rink_bookings (id, facility_id) on delete cascade,
  constraint locker_room_cleaning_tasks_assignment_fk
    foreign key (locker_room_assignment_id, facility_id)
    references public.rink_locker_room_assignments (id, facility_id) on delete cascade,
  constraint locker_room_cleaning_tasks_assignee_fk
    foreign key (assigned_employee_id, facility_id)
    references public.employees (id, facility_id) on delete set null (assigned_employee_id),
  constraint locker_room_cleaning_tasks_completed_by_fk
    foreign key (completed_by, facility_id)
    references public.employees (id, facility_id) on delete set null (completed_by),
  constraint locker_room_cleaning_tasks_lifecycle_chk check (
    (status = 'completed' and completed_at is not null and completed_by is not null
                          and cancelled_at is null)
    or (status = 'cancelled' and cancelled_at is not null and completed_at is null
                           and completed_by is null)
    or (status = 'scheduled' and completed_at is null and completed_by is null
                           and cancelled_at is null)
  )
);

comment on table public.locker_room_cleaning_tasks is
  'Facility-scoped locker-room cleaning work. Every lifecycle mutation is copied to audit_logs by trg_audit_locker_room_cleaning_tasks.';
comment on column public.locker_room_cleaning_tasks.change_origin is
  'Origin copied into the audit before/after image: employee, manager, system, or trigger. Automated reconciliation must set system or trigger.';

create index if not exists idx_locker_room_cleaning_tasks_facility_schedule
  on public.locker_room_cleaning_tasks (facility_id, scheduled_for);

create unique index if not exists idx_locker_room_cleaning_tasks_active_assignment
  on public.locker_room_cleaning_tasks (locker_room_assignment_id)
  where locker_room_assignment_id is not null and status = 'scheduled';

-- Keep the derived cleaning work in lockstep with the booking.  A tentative
-- booking is deliberately treated just like any other inactive source record:
-- it cannot create active work and a demotion from confirmed cancels both the
-- scheduled task and any notification which has not left the outbox yet.
create or replace function public.reconcile_locker_room_cleaning_task(
  p_assignment_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_booking       public.rink_bookings%rowtype;
  v_existing      public.locker_room_cleaning_tasks%rowtype;
  v_has_existing  boolean := false;
  v_task_id       uuid;
  v_employee_id   uuid;
  v_shift_id      uuid;
  v_route         text := 'unassigned';
  v_room_ids      uuid[];
  v_room_names    text[];
  v_due           timestamptz;
  v_timezone      text;
  v_message       text;
begin
  select * into v_booking
  from public.rink_bookings
  where id = p_booking_id
  for update;

  if not found then
    return;
  end if;

  select * into v_existing
  from public.locker_room_cleaning_tasks
  where booking_id = p_booking_id;
  v_has_existing := found;

  select
    array_agg(lr.id order by lr.sort_order, lr.name, lr.id),
    array_agg(lr.name order by lr.sort_order, lr.name, lr.id)
  into v_room_ids, v_room_names
  from public.rink_locker_room_assignments a
  join public.facility_locker_rooms lr
    on lr.id = a.locker_room_id and lr.facility_id = a.facility_id
  where a.booking_id = p_booking_id;

  -- Cancellation is retained as task history. Removing the final room has the
  -- same operational effect; re-adding a room reactivates the unique task.
  if v_booking.status = 'cancelled' or coalesce(cardinality(v_room_ids), 0) = 0 then
    update public.locker_room_cleaning_tasks
    set status = 'cancelled', cancelled_at = coalesce(cancelled_at, now()),
        completed_at = null,
        assigned_employee_id = null, assigned_shift_id = null,
        assignment_route = 'unassigned'
    where booking_id = p_booking_id and status <> 'cancelled'
    returning id into v_task_id;

    if v_task_id is not null then
      delete from public.schedule_notifications where cleaning_task_id = v_task_id;
  v_assignment public.rink_locker_room_assignments%rowtype;
  v_booking public.rink_bookings%rowtype;
  v_task_id uuid;
begin
  select * into v_assignment
    from public.rink_locker_room_assignments
   where id = p_assignment_id;

  if found then
    select * into v_booking
      from public.rink_bookings
     where id = v_assignment.booking_id
       and facility_id = v_assignment.facility_id;
  end if;

  if not found or v_booking.status <> 'confirmed' then
    update public.locker_room_cleaning_tasks
       set status = 'cancelled',
           cancelled_at = now(),
           cancellation_reason = 'source booking is not confirmed',
           change_origin = 'trigger'
     where locker_room_assignment_id = p_assignment_id
       and status = 'scheduled'
    returning id into v_task_id;

    if v_task_id is not null then
      update public.notification_outbox
         set status = 'cancelled'
       where source_module = 'locker_room_cleaning_tasks'
         and source_record_id = v_task_id
         and status = 'pending';
    end if;
    return;
  end if;

  -- Completed work is immutable history unless its source rental is cancelled
  -- or loses every locker room (handled above).
  if v_has_existing and v_existing.status = 'completed' then
    return;
  end if;

  v_due := v_booking.ends_at + interval '30 minutes';

  select s.employee_id, s.id
  into v_employee_id, v_shift_id
  from public.schedule_shifts s
  join public.employees e
    on e.id = s.employee_id and e.facility_id = s.facility_id and e.is_active
  join public.employee_departments ed
    on ed.employee_id = e.id and ed.department_id = s.department_id
       and ed.facility_id = s.facility_id
  join public.employee_job_area_assignments ejaa
    on ejaa.employee_id = e.id and ejaa.facility_id = s.facility_id
  join public.employee_job_areas ja
    on ja.id = ejaa.job_area_id and ja.facility_id = s.facility_id
       and ja.is_active and ja.slug = 'custodial'
  where s.facility_id = v_booking.facility_id
    and s.status = 'published'
    and s.starts_at <= v_due and s.ends_at > v_due
  order by ejaa.is_primary desc, s.starts_at desc, s.id
  limit 1;

  if v_employee_id is not null then
    v_route := 'custodial';
  else
    select s.employee_id, s.id
    into v_employee_id, v_shift_id
    from public.schedule_shifts s
    join public.employees e
      on e.id = s.employee_id and e.facility_id = s.facility_id and e.is_active
    join public.roles r
      on r.id = e.role_id and r.facility_id = e.facility_id and r.key = 'manager'
    join public.employee_departments ed
      on ed.employee_id = e.id and ed.department_id = s.department_id
         and ed.facility_id = s.facility_id
    where s.facility_id = v_booking.facility_id
      and s.status = 'published'
      and s.starts_at <= v_due and s.ends_at > v_due
    order by s.starts_at desc, s.id
    limit 1;
    if v_employee_id is not null then
      v_route := 'manager';
    end if;
  end if;

  -- Shift triggers may revisit many nearby tasks. Do not replace a read inbox
  -- item with an identical unread one when no task-visible value changed.
  if v_has_existing and v_existing.status = 'pending'
     and v_existing.assigned_employee_id is not distinct from v_employee_id
     and v_existing.assigned_shift_id is not distinct from v_shift_id
     and v_existing.scheduled_for = v_due
     and v_existing.locker_room_ids = v_room_ids
     and v_existing.locker_room_names = v_room_names
     and v_existing.assignment_route = v_route then
    return;
  end if;

  insert into public.locker_room_cleaning_tasks (
    facility_id, booking_id, assigned_employee_id, assigned_shift_id,
    scheduled_for, locker_room_ids, locker_room_names,
    assignment_route, status, cancelled_at, completed_at
  ) values (
    v_booking.facility_id, v_booking.id, v_employee_id, v_shift_id,
    v_due, v_room_ids, v_room_names, v_route, 'pending', null, null
  )
  on conflict (booking_id) do update set
    assigned_employee_id = excluded.assigned_employee_id,
    assigned_shift_id = excluded.assigned_shift_id,
    scheduled_for = excluded.scheduled_for,
    locker_room_ids = excluded.locker_room_ids,
    locker_room_names = excluded.locker_room_names,
    assignment_route = excluded.assignment_route,
    status = case when locker_room_cleaning_tasks.status = 'completed'
                  then 'completed' else 'pending' end,
    cancelled_at = case when locker_room_cleaning_tasks.status = 'completed'
                        then locker_room_cleaning_tasks.cancelled_at else null end
  returning id into v_task_id;

  -- Replace rather than append when the booking time, rooms or assignee change.
  delete from public.schedule_notifications where cleaning_task_id = v_task_id;
  if v_employee_id is not null then
    select timezone into v_timezone from public.facilities where id = v_booking.facility_id;
    v_message := format(
      'Clean %s at %s (%s).',
      array_to_string(v_room_names, ', '),
      to_char(v_due at time zone v_timezone, 'FMHH12:MI AM'),
      v_timezone
    );
    insert into public.schedule_notifications (
      facility_id, employee_id, notification_type, shift_id, cleaning_task_id, payload
    ) values (
      v_booking.facility_id, v_employee_id, 'locker_room_cleaning', v_shift_id, v_task_id,
      jsonb_build_object(
        'message', v_message, 'booking_id', v_booking.id,
        'scheduled_for', v_due,
        'timezone', v_timezone, 'locker_rooms', to_jsonb(v_room_names),
        'assignment_route', v_route
      )
    );
  select id into v_task_id
    from public.locker_room_cleaning_tasks
   where locker_room_assignment_id = p_assignment_id
     and status = 'scheduled';

  if v_task_id is null then
    insert into public.locker_room_cleaning_tasks
      (facility_id, locker_room_id, booking_id, locker_room_assignment_id,
       scheduled_for, change_origin)
    values
      (v_assignment.facility_id, v_assignment.locker_room_id,
       v_assignment.booking_id, v_assignment.id,
       v_assignment.occupies_until, 'trigger');
  else
    update public.locker_room_cleaning_tasks
       set locker_room_id = v_assignment.locker_room_id,
           booking_id = v_assignment.booking_id,
           scheduled_for = v_assignment.occupies_until,
           change_origin = 'trigger'
     where id = v_task_id;
  end if;
end;
$$;

comment on function public.reconcile_locker_room_cleaning_task(uuid) is
  'Idempotently creates, reschedules, reroutes or cancels the single cleaning task for a booking. Uses published shifts, active Custodial job-area assignments, matching departments, and the manager role fallback.';
revoke execute on function public.reconcile_locker_room_cleaning_task(uuid)
  from public, anon, authenticated;

create or replace function public.sync_locker_room_cleaning_from_booking()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  perform public.reconcile_locker_room_cleaning_task(coalesce(new.id, old.id));
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_booking()
  from public, anon, authenticated;

create or replace function public.sync_locker_room_cleaning_from_assignment()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if tg_op = 'UPDATE' and old.booking_id is distinct from new.booking_id then
    perform public.reconcile_locker_room_cleaning_task(old.booking_id);
  end if;
  perform public.reconcile_locker_room_cleaning_task(
    case when tg_op = 'DELETE' then old.booking_id else new.booking_id end
  );
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_assignment()
  from public, anon, authenticated;

create trigger trg_rink_booking_cleaning_sync
  after insert or update of ends_at, status on public.rink_bookings
  for each row execute function public.sync_locker_room_cleaning_from_booking();
create trigger trg_rink_locker_assignment_cleaning_sync
  after insert or update or delete on public.rink_locker_room_assignments
  for each row execute function public.sync_locker_room_cleaning_from_assignment();

-- A roster edit can change the best assignee after the rental was entered.
-- Re-run only pending work whose due instant falls within the changed shift;
-- this also lets a newly published shift claim a previously unassigned task.
create or replace function public.sync_locker_room_cleaning_from_shift()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_task record;
  v_facility_id uuid := coalesce(new.facility_id, old.facility_id);
  v_from timestamptz := least(
    coalesce(new.starts_at, old.starts_at), coalesce(old.starts_at, new.starts_at)
  );
  v_until timestamptz := greatest(
    coalesce(new.ends_at, old.ends_at), coalesce(old.ends_at, new.ends_at)
  );
begin
  for v_task in
    select t.booking_id
    from public.locker_room_cleaning_tasks t
    where t.facility_id = v_facility_id and t.status = 'pending'
      and t.scheduled_for >= v_from and t.scheduled_for < v_until
    order by t.booking_id
  loop
    perform public.reconcile_locker_room_cleaning_task(v_task.booking_id);
  end loop;
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_shift()
  from public, anon, authenticated;

create trigger trg_schedule_shift_cleaning_sync
  after insert or update of employee_id, starts_at, ends_at, status, department_id
  or delete on public.schedule_shifts
  for each row execute function public.sync_locker_room_cleaning_from_shift();

-- Qualification changes can make a current assignee ineligible or make a
-- Custodial employee newly preferable to the manager fallback. These tables
-- change much less often than shifts, so a facility-scoped pass is both
-- simpler and safer than attempting to infer every affected shift here.
create or replace function public.sync_locker_room_cleaning_from_workforce()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_task record;
  v_facility_id uuid := case
    when tg_op = 'DELETE' then old.facility_id
    else new.facility_id
  end;
begin
  for v_task in
    select t.booking_id
    from public.locker_room_cleaning_tasks t
    where t.facility_id = v_facility_id and t.status = 'pending'
    order by t.booking_id
  loop
    perform public.reconcile_locker_room_cleaning_task(v_task.booking_id);
  end loop;
  return coalesce(new, old);
end;
$$;
revoke execute on function public.sync_locker_room_cleaning_from_workforce()
  from public, anon, authenticated;

create trigger trg_employee_cleaning_sync
  after update of is_active, role_id on public.employees
  for each row execute function public.sync_locker_room_cleaning_from_workforce();
create trigger trg_employee_department_cleaning_sync
  after insert or update or delete on public.employee_departments
  for each row execute function public.sync_locker_room_cleaning_from_workforce();
create trigger trg_employee_job_area_assignment_cleaning_sync
  after insert or update or delete on public.employee_job_area_assignments
  for each row execute function public.sync_locker_room_cleaning_from_workforce();
create trigger trg_employee_job_area_cleaning_sync
  after update of is_active, slug on public.employee_job_areas
  for each row execute function public.sync_locker_room_cleaning_from_workforce();

-- Existing confirmed rentals receive tasks during rollout.
do $$
declare v_booking_id uuid;
begin
  for v_booking_id in
    select distinct b.id
    from public.rink_bookings b
    join public.rink_locker_room_assignments a on a.booking_id = b.id
    where b.status <> 'cancelled'
  loop
    perform public.reconcile_locker_room_cleaning_task(v_booking_id);
revoke execute on function public.reconcile_locker_room_cleaning_task(uuid)
  from public, anon, authenticated;

create or replace function public.reconcile_locker_room_cleaning_task_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_assignment record;
begin
  if tg_table_name = 'rink_locker_room_assignments' then
    perform public.reconcile_locker_room_cleaning_task(coalesce(new.id, old.id));
  else
    for v_assignment in
      select id from public.rink_locker_room_assignments
       where booking_id = coalesce(new.id, old.id)
    loop
      perform public.reconcile_locker_room_cleaning_task(v_assignment.id);
    end loop;
  end if;
  return coalesce(new, old);
end;
$$;

revoke execute on function public.reconcile_locker_room_cleaning_task_trigger()
  from public, anon, authenticated;

drop trigger if exists trg_reconcile_locker_room_cleaning_assignment
  on public.rink_locker_room_assignments;
create trigger trg_reconcile_locker_room_cleaning_assignment
  after insert or update on public.rink_locker_room_assignments
  for each row execute function public.reconcile_locker_room_cleaning_task_trigger();

drop trigger if exists trg_reconcile_locker_room_cleaning_booking
  on public.rink_bookings;
create trigger trg_reconcile_locker_room_cleaning_booking
  after update of status on public.rink_bookings
  for each row execute function public.reconcile_locker_room_cleaning_task_trigger();

-- Existing confirmed rentals receive tasks during rollout.
do $$
declare
  v_assignment record;
begin
  for v_assignment in
    select a.id
      from public.rink_locker_room_assignments a
      join public.rink_bookings b
        on b.id = a.booking_id and b.facility_id = a.facility_id
     where b.status = 'confirmed'
  loop
    perform public.reconcile_locker_room_cleaning_task(v_assignment.id);
  end loop;
end;
$$;

alter table public.locker_room_cleaning_tasks enable row level security;

drop trigger if exists trg_locker_room_cleaning_tasks_updated_at
  on public.locker_room_cleaning_tasks;
create trigger trg_locker_room_cleaning_tasks_updated_at
  before update on public.locker_room_cleaning_tasks
  for each row execute function public.set_updated_at();

alter table public.locker_room_cleaning_tasks enable row level security;

drop policy if exists locker_room_cleaning_tasks_select
  on public.locker_room_cleaning_tasks;
create policy locker_room_cleaning_tasks_select on public.locker_room_cleaning_tasks
  for select to authenticated
  using (
    public.is_super_admin()
    or (facility_id = public.current_facility_id() and (
      assigned_employee_id = public.current_employee_id()
      or public.has_module_edit_access('rink_scheduling')
    ))
  );
create policy locker_room_cleaning_tasks_update on public.locker_room_cleaning_tasks
  for update to authenticated
  using (
    public.is_super_admin()
    or (facility_id = public.current_facility_id() and (
      assigned_employee_id = public.current_employee_id()
      or public.has_module_edit_access('rink_scheduling')
    ))
  )
  with check (public.is_super_admin() or facility_id = public.current_facility_id());

-- Triggers own creation/cancellation; clients cannot forge or delete generated work.
revoke insert, delete on public.locker_room_cleaning_tasks from anon, authenticated;
    or (facility_id = public.current_facility_id()
        and public.has_module_access('rink_scheduling'))
  );

drop policy if exists locker_room_cleaning_tasks_write
  on public.locker_room_cleaning_tasks;
create policy locker_room_cleaning_tasks_write on public.locker_room_cleaning_tasks
  for all to authenticated
  using (
    public.is_super_admin()
    or (facility_id = public.current_facility_id()
        and public.has_module_edit_access('rink_scheduling'))
  )
  with check (
    public.is_super_admin()
    or (facility_id = public.current_facility_id()
        and public.has_module_edit_access('rink_scheduling'))
  );

drop trigger if exists trg_audit_locker_room_cleaning_tasks
  on public.locker_room_cleaning_tasks;
create trigger trg_audit_locker_room_cleaning_tasks
  after insert or update or delete on public.locker_room_cleaning_tasks
  for each row execute function public.audit_row_change();

commit;
